# GLOBAL STUFF
experiment_id: Ultrapixel_controlnet

checkpoint_path: checkpoint output path
output_path:  visual results output path
model_version: 3.6B
dtype: float32
# # WandB
# wandb_project: StableCascade
# wandb_entity: wandb_username
#module_filters: ['.depthwise', '.mapper', '.attn', '.channelwise' ]
#rank: 32
# TRAINING PARAMS
lr: 1.0e-4
batch_size: 12
#image_size: [1536, 2048, 2560, 3072, 4096]
image_size: [1024, 2048, 2560, 3072, 3584, 3840, 4096, 4608]
#image_size: [  1024, 1536, 2048, 2560,  3072, 3584, 3840, 4096, 4608]
#image_size: [  1024, 1280]
multi_aspect_ratio: [1/1, 1/2, 1/3, 2/3, 3/4, 1/5, 2/5, 3/5, 4/5, 1/6, 5/6, 9/16]
grad_accum_steps: 2
updates: 40000
backup_every: 5000
save_every: 256
warmup_updates: 1
use_fsdp: True

# ControlNet specific
controlnet_blocks: [0, 4, 8, 12, 51, 55, 59, 63]
controlnet_filter: CannyFilter
controlnet_filter_params: 
  resize: 224
# offset_noise: 0.1

# GDF
adaptive_loss_weight: True

ema_start_iters: 10
ema_iters: 50
ema_beta: 0.9

webdataset_path: path to your training dataset
effnet_checkpoint_path: models/effnet_encoder.safetensors
previewer_checkpoint_path: models/previewer.safetensors
generator_checkpoint_path: models/stage_c_bf16.safetensors
controlnet_checkpoint_path: pretrained controlnet path

