# GLOBAL STUFF
experiment_id: roubao_cat_personalized

checkpoint_path: checkpoint output path
output_path:  visual results output path
model_version: 3.6B
dtype: float32

module_filters: [ '.attn']
rank: 4
train_tokens:
  # - ['^snail', null] # token starts with "snail" -> "snail" & "snails", don't need to be reinitialized
  - ['[roubaobao]', '^cat</w>'] # custom token [snail], initialize as avg of snail & snails
# TRAINING PARAMS
lr: 1.0e-4
batch_size: 4

image_size: [1024, 2048, 2560, 3072, 3584, 3840, 4096, 4608]
multi_aspect_ratio: [1/1, 1/2, 1/3, 2/3, 3/4, 1/5, 2/5, 3/5, 4/5, 1/6, 5/6, 9/16]
grad_accum_steps: 2
updates: 40000
backup_every: 5000
save_every: 512
warmup_updates: 1
use_ddp: True

# GDF
adaptive_loss_weight: True


tmp_prompt: a photo of a cat [roubaobao]
webdataset_path: path to your personalized training dataset
effnet_checkpoint_path:  models/effnet_encoder.safetensors
previewer_checkpoint_path:  models/previewer.safetensors
generator_checkpoint_path:  models/stage_c_bf16.safetensors
ultrapixel_path: models/ultrapixel_t2i.safetensors

