# GLOBAL STUFF
experiment_id: ultrapixel_t2i
#strc_fixlrt_norm3_lite_1024_hrft_newdata
checkpoint_path: checkpoint output path   #output model directory
output_path: visual results output path       #experiment output directory
model_version: 3.6B    # finetune large  stage c model of stablecascade
dtype: float32


# TRAINING PARAMS
lr: 1.0e-4
batch_size: 4   # gpu_number * num_per_gpu * grad_accum_steps
image_size: [1024, 2048, 2560, 3072, 3584, 3840, 4096, 4608]  # possible image resolution
multi_aspect_ratio: [1/1, 1/2, 1/3, 2/3, 3/4, 1/5, 2/5, 3/5, 4/5, 1/6, 5/6, 9/16]
grad_accum_steps: 2
updates: 40000
backup_every: 5000
save_every: 256
warmup_updates: 1
use_ddp: True

# GDF
adaptive_loss_weight: True


webdataset_path: path to your personalized training dataset
effnet_checkpoint_path: models/effnet_encoder.safetensors
previewer_checkpoint_path: models/previewer.safetensors
generator_checkpoint_path: models/stage_c_bf16.safetensors